export const pageTexts = {
  beginTextJost: <>QUER DESCOBRIR <br/>OS PRODUTOS <br/>IDEAIS PARA A</>,
  beginText: <>SUA ROTINA <br />DE SKINCARE?</>,
  beginButton: 'QUERO! >',
  chooseSkinTypeTextJost: "ENTÃO VAMOS LÁ. QUAL É O SEU",
  chooseSkinTypeText: "TIPO DE PELE?",
  create_routine_jost: <>VAMOS CRIAR O SEU RITUAL DE <span>SKINCARE DIÁRIO?</span></>,
  create_routine: "SÓ SE FOR AGORA!",
  routine_description: "ESSA É A COMBINAÇÃO IDEAL PRA VOCÊ:",
  combination_first_page_jost_text: <>VOCÊ OBSERVA <br /> UMA OLEOSIDADE <br /> EXCESSIVA NA ZONA T <br /> DO ROSTO, QUE PEDE ALGUNS CUIDADOS ESPECÍFICOS?</>,
  first_page_description_text: <>Ainda bem que a curadoria <br />da BLZ conta com as melhores marcas para você combinar e criar uma rotina personalizada para a sua pele.</>,
  daytime_routine: 'ROTINA DIURNA',
  night_routine: 'ROTINA NOTURNA',
  end_title: 'OBRIGADA!',
  end_description: 'AGORA QUE VOCÊ JÁ DESCOBRIU A ROTINA IDEAL PARA A SUA PELE, APROVEITE A LOJA PARA CONFERIR DE PERTO OS NOSSOS PRODUTOS.',
  dry_skin_jost:<>SE O SEU ROSTO É <br/> RESSECADO, É MUITO <br/> IMPORTANTE MANTER <br/> A HIDRATAÇÃO EM DIA <br/> E OPTAR POR SABONETES <br/> SEM ÁLCOOL OU SULFATO, TÁ?</>,
  dry_skin_alternate: 'CUIDADOS EXTRAS,',
  dry_skin_end: 'POR EXEMPLO, ESCOLHER UM LIMPADOR FACIAL SEM ÁLCOOL OU SULFATO.',
  normal_title: 'O SEU ROSTO NÃO APRESENTA EXCESSO DE BRILHO, POROS DILATADOS NEM RESSECAMENTO, NÉ?',
  normal_end: 'Mesmo assim, requer cuidados especiais.',
  oily_title: <>O SEU ROSTO TEM UM BRILHO INTENSO, <br/>POROS DILATADOS E TENDÊNCIA À ACNE?</>,
}